### ISSUE TITLE
The user should be able to select a PDF from the file system

### ISSUE THREAD

**Issue by tormodAase** [equinor/mad-expense-and-pay-app#60] opened 2022-04-07 11:00 UTC
Currently the user can only select images as attachment from the device. The user should also be able to select PDFs.

**Test Requirements**
- [ ]  Able to add PDF as attachment
- [ ]  PDF attachments should have a logo that indicates that the file is PDF
- [ ]  The only supported file types to add is JPG, JPEG, PNG and PDF. Others files types should be blocked from selecting.

![Image](https://user-images.githubusercontent.com/99209297/173865731-86329bf1-afdf-4d1c-b414-36d6ec9b9c97.png)

**Comment by dbjoEq** [comment] 2022-06-15 15:29
@ntorsen 👋 
This is feature is ready to be tested in QA. Build number: 32574. 😊

**Comment by ntorsen** [comment] 2022-06-16 07:35
**Tested with build 32574. What is working good:**
- Able to add PDF as attachment
- PDF attachment have a logo that indicates that the file is PDF
- Tested with file type PDF and take photo for both travel expense and expense recording, finding the same result for both parts
- Able to find PDF file and other attachments in SAP after they have been synced
![image](https://user-images.githubusercontent.com/89014017/174008179-5331b4d3-599f-45d5-98e2-c7df61468274.png)

**Remarks:**
- When you create a new travel expense/expense recording and take a photo - the text Captured Attachment falls into the image:
![image](https://user-images.githubusercontent.com/89014017/174007030-8f727a6c-fc1a-4538-83d8-a64d3b73455c.png)

This also happens when you look at Summary:
![image](https://user-images.githubusercontent.com/89014017/174007125-bb005c9e-25bd-47e0-9d6b-75bc73908c20.png)

- If you leave travel/expense in draft or confirm and send, and go back into it - it will not look as described above, it will look has intended. 
![image](https://user-images.githubusercontent.com/89014017/174008004-cac78938-4691-4ff2-85b8-0af42c913f39.png)
![image](https://user-images.githubusercontent.com/89014017/174008052-5759e683-41ca-42ec-a6c2-e330dfd482f0.png)

- Not sure how to add file types JPG, JPEG and PNG. Seems like my phone don't save images of the sort to my documents after being saved... But by taking a photo, isn't that a jpg file itself? Might need some help with this...

@dbjoEq

**Comment by dbjoEq** [comment] 2022-06-16 07:42
@ntorsen 😊 
Good catch! Moving it back to in progress, will let you know when there is a new version ready for testing. 😉

**Closed** 2022-06-17 08:23 UTC
Labels: enhancement
